import { Timestamp } from 'firebase/firestore';
import { Employee, Lead, Task, CallOutcome } from '@/types';

// Helper to create Firestore-like Timestamps
const now = () => Timestamp.fromDate(new Date());
const daysAgo = (days: number) => Timestamp.fromDate(new Date(Date.now() - days * 24 * 60 * 60 * 1000));
const hoursAgo = (hours: number) => Timestamp.fromDate(new Date(Date.now() - hours * 60 * 60 * 1000));

// ============ MOCK EMPLOYEES ============

export const mockEmployees: Employee[] = [
    {
        id: 'emp-admin-001',
        email: 'admin@demo.com',
        name: 'Admin User',
        phone: '9876543210',
        role: 'ADMIN',
        isActive: true,
        dailyCallTarget: 30,
        createdAt: daysAgo(90),
        updatedAt: daysAgo(1),
        lastLoginAt: hoursAgo(2),
    },
    {
        id: 'emp-counsellor-001',
        email: 'priya@demo.com',
        name: 'Priya Sharma',
        phone: '9876543211',
        role: 'COUNSELLOR',
        isActive: true,
        dailyCallTarget: 25,
        createdAt: daysAgo(60),
        updatedAt: daysAgo(5),
        lastLoginAt: hoursAgo(1),
    },
    {
        id: 'emp-counsellor-002',
        email: 'rahul@demo.com',
        name: 'Rahul Kumar',
        phone: '9876543212',
        role: 'COUNSELLOR',
        isActive: true,
        dailyCallTarget: 30,
        createdAt: daysAgo(45),
        updatedAt: daysAgo(3),
        lastLoginAt: hoursAgo(4),
    },
    {
        id: 'emp-counsellor-003',
        email: 'anjali@demo.com',
        name: 'Anjali Patel',
        phone: '9876543213',
        role: 'COUNSELLOR',
        isActive: true,
        dailyCallTarget: 20,
        createdAt: daysAgo(30),
        updatedAt: daysAgo(2),
        lastLoginAt: daysAgo(1),
    },
];

// ============ MOCK LEADS ============

export const mockLeads: Lead[] = [
    // Bulk leads (Pipeline A)
    {
        id: 'lead-001',
        name: 'Amit Singh',
        mobile: '9812345001',
        email: 'amit.singh@email.com',
        source: 'BULK',
        priority: 'HIGH',
        currentStage: 'NEW',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
        course: 'Full Stack Development',
        location: 'Mumbai',
    },
    {
        id: 'lead-002',
        name: 'Sneha Gupta',
        mobile: '9812345002',
        source: 'BULK',
        priority: 'MEDIUM',
        currentStage: 'NEW',
        createdAt: daysAgo(3),
        updatedAt: daysAgo(3),
        course: 'Data Science',
        location: 'Delhi',
    },
    {
        id: 'lead-003',
        name: 'Vikram Mehta',
        mobile: '9812345003',
        email: 'vikram.m@email.com',
        source: 'BULK',
        priority: 'LOW',
        currentStage: 'CONTACTED',
        assignedEmployeeId: 'emp-counsellor-001',
        createdAt: daysAgo(5),
        updatedAt: daysAgo(1),
        course: 'Digital Marketing',
        location: 'Bangalore',
    },
    {
        id: 'lead-004',
        name: 'Pooja Reddy',
        mobile: '9812345004',
        source: 'BULK',
        priority: 'HIGH',
        currentStage: 'QUALIFIED',
        assignedEmployeeId: 'emp-counsellor-001',
        createdAt: daysAgo(7),
        updatedAt: daysAgo(1),
        course: 'Cloud Computing',
        location: 'Hyderabad',
    },
    {
        id: 'lead-005',
        name: 'Karan Joshi',
        mobile: '9812345005',
        source: 'BULK',
        priority: 'MEDIUM',
        currentStage: 'NEW',
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
        course: 'UI/UX Design',
        location: 'Pune',
    },
    // Application leads (Pipeline B)
    {
        id: 'lead-app-001',
        name: 'Riya Kapoor',
        mobile: '9812345101',
        email: 'riya.k@email.com',
        source: 'APPLICATION',
        applicationNumber: 'APP2024001',
        priority: 'HIGH',
        currentStage: 'CONTACTED',
        assignedEmployeeId: 'emp-counsellor-002',
        createdAt: daysAgo(4),
        updatedAt: hoursAgo(6),
        course: 'MBA',
    },
    {
        id: 'lead-app-002',
        name: 'Arjun Nair',
        mobile: '9812345102',
        email: 'arjun.n@email.com',
        source: 'APPLICATION',
        applicationNumber: 'APP2024002',
        priority: 'HIGH',
        currentStage: 'QUALIFIED',
        assignedEmployeeId: 'emp-counsellor-002',
        createdAt: daysAgo(6),
        updatedAt: daysAgo(1),
        course: 'BBA',
    },
    {
        id: 'lead-app-003',
        name: 'Meera Iyer',
        mobile: '9812345103',
        source: 'APPLICATION',
        applicationNumber: 'APP2024003',
        priority: 'MEDIUM',
        currentStage: 'NEW',
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
        course: 'B.Tech',
    },
    {
        id: 'lead-app-004',
        name: 'Sanjay Verma',
        mobile: '9812345104',
        email: 'sanjay.v@email.com',
        source: 'APPLICATION',
        applicationNumber: 'APP2024004',
        priority: 'LOW',
        currentStage: 'CONTACTED',
        assignedEmployeeId: 'emp-counsellor-001',
        createdAt: daysAgo(3),
        updatedAt: daysAgo(2),
        course: 'M.Tech',
    },
    {
        id: 'lead-app-005',
        name: 'Divya Sharma',
        mobile: '9812345105',
        source: 'APPLICATION',
        applicationNumber: 'APP2024005',
        priority: 'HIGH',
        currentStage: 'CONVERTED',
        assignedEmployeeId: 'emp-counsellor-003',
        createdAt: daysAgo(10),
        updatedAt: daysAgo(2),
        course: 'BCA',
    },
];

// ============ MOCK TASKS ============

export const mockTasks: Task[] = [
    {
        id: 'task-001',
        employeeId: 'emp-counsellor-001',
        leadId: 'lead-003',
        leadName: 'Vikram Mehta',
        taskType: 'FOLLOW_UP',
        pipeline: 'BULK',
        status: 'PENDING',
        dueDate: Timestamp.fromDate(new Date(Date.now() + 2 * 60 * 60 * 1000)), // 2 hours from now
        notes: 'Follow up on course interest',
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
    },
    {
        id: 'task-002',
        employeeId: 'emp-counsellor-001',
        leadId: 'lead-app-004',
        leadName: 'Sanjay Verma',
        taskType: 'FOLLOW_UP',
        pipeline: 'FOLLOW_UP',
        status: 'OVERDUE',
        dueDate: daysAgo(1),
        notes: 'Check document status',
        createdAt: daysAgo(3),
        updatedAt: daysAgo(1),
    },
    {
        id: 'task-003',
        employeeId: 'emp-counsellor-002',
        leadId: 'lead-app-001',
        leadName: 'Riya Kapoor',
        taskType: 'FOLLOW_UP',
        pipeline: 'FOLLOW_UP',
        status: 'PENDING',
        dueDate: Timestamp.fromDate(new Date(Date.now() + 4 * 60 * 60 * 1000)), // 4 hours from now
        notes: 'Confirm admission date',
        createdAt: hoursAgo(12),
        updatedAt: hoursAgo(6),
    },
    {
        id: 'task-004',
        employeeId: 'emp-counsellor-002',
        leadId: 'lead-app-002',
        leadName: 'Arjun Nair',
        taskType: 'CALL',
        pipeline: 'FOLLOW_UP',
        status: 'COMPLETED',
        dueDate: daysAgo(1),
        completedAt: daysAgo(1),
        notes: 'Called and confirmed enrollment',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(1),
    },
];

// ============ MOCK CALL OUTCOMES ============

export const mockCallOutcomes: CallOutcome[] = [
    {
        id: 'outcome-001',
        leadId: 'lead-003',
        employeeId: 'emp-counsellor-001',
        pipeline: 'BULK',
        connected: true,
        interestLevel: 'MEDIUM',
        readiness: 'NEXT_MONTH',
        nextAction: 'FOLLOW_UP',
        followUpDate: Timestamp.fromDate(new Date(Date.now() + 2 * 60 * 60 * 1000)),
        notes: 'Interested but needs time to decide. Suggest following up next week.',
        callDuration: 180,
        createdAt: daysAgo(1),
    },
    {
        id: 'outcome-002',
        leadId: 'lead-004',
        employeeId: 'emp-counsellor-001',
        pipeline: 'BULK',
        connected: true,
        interestLevel: 'HIGH',
        readiness: 'READY_NOW',
        nextAction: 'CLOSE_QUALIFIED',
        notes: 'Very interested, ready to enroll next week.',
        callDuration: 420,
        createdAt: daysAgo(2),
    },
    {
        id: 'outcome-003',
        leadId: 'lead-app-001',
        employeeId: 'emp-counsellor-002',
        pipeline: 'FOLLOW_UP',
        connected: true,
        interestLevel: 'HIGH',
        readiness: 'READY_NOW',
        nextAction: 'FOLLOW_UP',
        followUpDate: Timestamp.fromDate(new Date(Date.now() + 4 * 60 * 60 * 1000)),
        notes: 'Waiting for document verification. Will call back.',
        callDuration: 240,
        createdAt: hoursAgo(6),
    },
    {
        id: 'outcome-004',
        leadId: 'lead-app-002',
        employeeId: 'emp-counsellor-002',
        pipeline: 'FOLLOW_UP',
        connected: true,
        interestLevel: 'HIGH',
        readiness: 'READY_NOW',
        nextAction: 'CLOSE_QUALIFIED',
        notes: 'Confirmed enrollment. Sending welcome kit.',
        callDuration: 300,
        createdAt: daysAgo(1),
    },
    {
        id: 'outcome-005',
        leadId: 'lead-001',
        employeeId: 'emp-counsellor-001',
        pipeline: 'BULK',
        connected: false,
        nextAction: 'FOLLOW_UP',
        followUpDate: Timestamp.fromDate(new Date(Date.now() + 24 * 60 * 60 * 1000)),
        notes: 'No answer, will try again tomorrow.',
        createdAt: hoursAgo(2),
    },
];

// ============ DEMO USER CREDENTIALS ============

export const DEMO_USERS = {
    admin: { email: 'admin@demo.com', password: 'demo123' },
    counsellor1: { email: 'priya@demo.com', password: 'demo123' },
    counsellor2: { email: 'rahul@demo.com', password: 'demo123' },
};
